### ISSUE TITLE
Fields not populating into template using Swift sample code

### ISSUE THREAD

**Issue by areckkimo** [docusign/native-ios-sdk#43] opened 2020-08-06 07:18 UTC
**Information**

iOS version: 13.3
DocuSign SDK version: 2.3.4
Sample Code: swift

**Problems**
First, I download "docusign-sdk-sample-swift" from https://github.com/docusign/native-ios-sdk/tree/release/2.3.4/docusign-sdk-sample-swift, second, I follow the tutorial (https://developers.docusign.com/ios_sdk/developer.html) to edit the relative code of the swift sample project and create a new template. Finally, I build it successfully, but the tabData doesn't populate into the template. Every text filed only shows "Text" in the offline model. I have confirmed that tabKey_**** variables equal to Data Lable of the text field in the template.

The id of the template is the same as the parameter of code.

<img width="628" alt="41634217-1CA7-4913-9D24-587FD771322A" src="https://user-images.githubusercontent.com/9306247/89501694-5d920a00-d7f6-11ea-9288-aa58b317d9a0.png">
<img width="1008" alt="5245F752-CA71-4F55-A1B5-1C8139295985" src="https://user-images.githubusercontent.com/9306247/89501720-68e53580-d7f6-11ea-9689-e8fbde1da10a.png">

The value of the data label is the same as key of tabData variable in the code.

<img width="987" alt="B7C55C0D-46B1-4A15-A6CA-6478FBD98036" src="https://user-images.githubusercontent.com/9306247/89501967-ce392680-d7f6-11ea-82cb-09fa0a5058f2.png">
<img width="1001" alt="C975203B-30AB-406A-A45A-924297411E1F" src="https://user-images.githubusercontent.com/9306247/89501977-d1ccad80-d7f6-11ea-903d-2710232db829.png">

**Comment by ashokds** [comment] 2020-08-06 16:57
Hi @areckkimo ,

Our team is taking a look. 
Are you also passing a valid `recipientData`? Could you please add those details as well.

Thanks,
Ashok

**Comment by ashokds** [comment] 2020-08-06 18:11
Hi @areckkimo : 

Adding some more details related to pass a valid recipient defaults object.

Here is an example of the account that contains the Template, and this account will be the host for IPS (In Person Signer).
<img width="302" alt="Account-name-email" src="https://user-images.githubusercontent.com/17131511/89566022-44786180-d7d4-11ea-908c-885964136dde.png">

Details from the Template with an IPS added with `roleName` (`IPS1`).
<img width="845" alt="template-rolename-name-hostname-hostemail" src="https://user-images.githubusercontent.com/17131511/89566025-45a98e80-d7d4-11ea-8116-ce4cbf809fcf.png">

With reference to above account & template details, following code sample can be used to pass a valid recipient default for IPS (In Person Signers).

```
        let recipientDatum = DSMRecipientDefault()
        recipientDatum.recipientRoleName = "IPS1"
        recipientDatum.recipientSelectorType = .recipientRoleName
        recipientDatum.recipientType = .inPersonSigner
        // In-person-signer name
        recipientDatum.inPersonSignerName = "Jane IPS Doe"
        // Host name (must match the name on the account) and email
        recipientDatum.recipientName = "Triston Gilbert"
        recipientDatum.recipientEmail = "xy_demo@dsxtr.com"
        return [recipientDatum]
```

Do you have a use case where you need to just pass the tab defaults and not the recipient defaults?

Thanks.

**Comment by areckkimo** [comment] 2020-08-07 03:09
> Hi @areckkimo ,
> 
> Our team is taking a look.
> Are you also passing a valid `recipientData`? Could you please add those details as well.
> 
> Thanks,



> Hi @areckkimo ,
> 
> Our team is taking a look.
> Are you also passing a valid `recipientData`? Could you please add those details as well.
> 
> Thanks,

Dear ashokds:

The recipientData is 0 value.
![Jietu20200807-110744](https://user-images.githubusercontent.com/9306247/89604712-69d1a200-d89e-11ea-8972-5d43dde018cf.jpg)

**Comment by areckkimo** [comment] 2020-08-07 03:19
> Hi @areckkimo :
> 
> As of the current SDK version `v2.3.4`, applying the TabDefaults (`tabData`) also requires RecipientDefault (`recipientData`) object to be supplied.
> 
> Adding some more details related to passing a valid recipient defaults object.
> 
> Here is an example of the account that contains the Template, and this account will be the host for IPS (In Person Signer).
> <img alt="Account-name-email" width="302" src="https://user-images.githubusercontent.com/17131511/89566022-44786180-d7d4-11ea-908c-885964136dde.png">
> 
> Details from the Template with an IPS added with `roleName` (`IPS1`).
> <img alt="template-rolename-name-hostname-hostemail" width="845" src="https://user-images.githubusercontent.com/17131511/89566025-45a98e80-d7d4-11ea-8116-ce4cbf809fcf.png">
> 
> With reference to the above account & template details, the following code sample from swift-app can be used to pass a valid recipient default for IPS (In Person Signers).
> 
> ```
>         let recipientDatum = DSMRecipientDefault()
>         recipientDatum.recipientRoleName = "IPS1"
>         recipientDatum.recipientSelectorType = .recipientRoleName
>         recipientDatum.recipientType = .inPersonSigner
>         // In-person-signer name
>         recipientDatum.inPersonSignerName = "Jane IPS Doe"
>         // Host name (must match the name on the account) and email
>         recipientDatum.recipientName = "Triston Gilbert"
>         recipientDatum.recipientEmail = "xy_demo@dsxtr.com"
>         return [recipientDatum]
> ```
> 
> [Recipient Default](https://github.com/docusign/native-ios-sdk/blob/master/DocuSignSDK.framework/Headers/DSMRecipientDefault.h)
> 
> Do you have a use case where you need to just pass the tab defaults and not the recipient defaults?
> 
> Thanks.

Dear @ashokds 

I would like to implement the case like the case of this video. https://youtu.be/mSS-07bLHnc?t=835
but when I set the receipt as 'Needs to Sign', leading to `tabData` not populating into the template.

**Comment by ashokds** [comment] 2020-08-07 20:41
Hi @areckkimo :

Thanks for adding the details related to `recipientData`. 

> The recipientData is 0 value.
> ![Jietu20200807-110744](https://user-images.githubusercontent.com/9306247/89604712-69d1a200-d89e-11ea-8972-5d43dde018cf.jpg)

^ This indeed is the root cause that's resulting in the `tabData` not getting populated in your app. If the client app doesn't set a valid `recipientData: [DSMRecipientDefault]` (count should be non-zero), the `tabData dictionary` is also not applied.

Did you try adding a DSMRecipientDefault object to the recipientData array? 

You may modify and use the following section in swift sample app. Please refer to the [previous comment](https://github.com/docusign/native-ios-sdk/issues/43#issuecomment-670092132) to ensure the validity of the name/email/roleName when preparing `DSMRecipientDefault` object.
```
/**
     Returns Array of the recipient data that will be passed into the template
     */
    func getTemplateRecipientData(templateId:String) -> Array<DSMRecipientDefault>
    {
        if templateId != "-your-template-id" {
            NSLog("Warning: Recipient Data not found for given templateId. Returning empty data.")
            return []
        }
        
        let recipientDatum = DSMRecipientDefault()
        recipientDatum.recipientRoleName = "IPS1"
        recipientDatum.recipientSelectorType = .recipientRoleName
        recipientDatum.recipientType = .inPersonSigner
        // In-person-signer name
        recipientDatum.inPersonSignerName = "Jane IPS Doe"
        // Host name (must match the name on the account) and email
        recipientDatum.recipientName = "Triston Gilbert"
        recipientDatum.recipientEmail = "xy_demo@dsxtr.com"
        return [recipientDatum]
    }
```

FYI: In the [video link](https://youtu.be/mSS-07bLHnc?t=835), [Allura Objective-C sample app](https://github.com/docusign/native-ios-sdk/tree/master/docusign-sdk-sample-objc) is used to demo the functionality of setting the default values for recipients & tabs prior to starting the signing. There too, the [TemplateManager](https://github.com/docusign/native-ios-sdk/blob/master/docusign-sdk-sample-objc/docusign-sdk-sample-objc/Managers/TemplatesManager.m) sets the defaults objects (both recipient & tab) prior to invoking `presentSendTemplateControllerWithTemplateWithId`.

Please do let know how it goes after passing non-empty `recipientData`. 
Thanks

**Comment by LarryKlugerDS** [comment] 2020-11-02 13:38
Closing due to age of last activity. 
Please respond if this is still an issue.
Thank you.

**Closed by LarryKlugerDS** 2020-11-02 13:38 UTC
Labels: help wanted
