### ISSUE TITLE
Black Background while Initiating Template

### ISSUE THREAD

**Issue by prakshapan** [docusign/native-ios-sdk#48] opened 2020-09-27 07:10 UTC
Hello, We have been looking for a PDF Document Signer and stumbled upon your SDK and   been experimenting with the provided SDK to check if it fits our needs. However I have been facing following issues :-

1) While loading Template for confirmation the background goes completely black, is this normal?
<img width="325" alt="Screen Shot 2020-09-27 at 12 47 01 PM" src="https://user-images.githubusercontent.com/20414478/94358338-f68b2600-00bf-11eb-863e-22abd8f6520a.png">

2) I have locked our application to only Portrait and seems like Signature view needs Landscape view and crashes there. Is there a way where I can give just the SDK access of the orientation to landscape or if the signature could work with Portrait mode.

Mind you the application where i'm trying to integrate is developed solely on SwiftUI. 
Thank you for your time.

**Comment by ashokds** [comment] 2020-09-29 20:32
Hi @prakshapan ,

> 1. While loading Template for confirmation the background goes completely black, is this normal?

SDK as of `v2.3.5` doesn't support `Dark Mode`. Please confim if the issue persist after switching to `light-mode`. It would help to share more details on your integration, so that we may prioritize it. 

> 2. I have locked our application to only Portrait and seems like Signature view needs Landscape view and crashes there. Is there a way where I can give just the SDK access of the orientation to landscape or if the signature could work with Portrait mode.

It supports the Only Portrait mode on iPhone, there are a few code changes required on the host-app to accomplish it. I'll follow up with a link to a guide that would help you get this functionality. 

> Mind you the application where i'm trying to integrate is developed solely on SwiftUI.

Only Swift based apps are fully supported. For the app that's using only SwiftUI, if it persists after disabing `dark-mode`, would it be possible for you to share code-snippet to reproduce this issue? 

Thank you.

**Comment by ashokds** [comment] 2020-10-07 05:03
Hi @prakshapan , Waiting for response.

**Comment by prakshapan** [comment] 2020-10-07 08:02
Hello @ashokds ,
Thank you for following up and sorry for the late response. 
I have integrated DocuSign (2.3.5) with following configuration.

Xcode: 11.5
Simulator: iPhone X (13.5)
Dark Mode/Appearance is turned off.
Also I have used
User Interface Style: Light  in Info.plist.
Still the issue persist. 
 For implementation I am wrapping the Viewcontroller in a UIViewControllerRepresentable to make it accessible in SwiftUI and then have hooked it up with DSMTemplateManager to present specific Docusign Template with signingMode online.
Let me know if you need more information.

Could you follow up with the link to the changes that should me made to the host app for the orientation? 
Thanks.

**Comment by LarryKlugerDS** [comment] 2020-11-02 13:37
Closing due to age of last activity. 
Please respond if this is still an issue.
Thank you.

**Closed by LarryKlugerDS** 2020-11-02 13:37 UTC
Labels: help wanted
