### ISSUE TITLE
Present a signing screen for an envelop Id created by Server

### ISSUE THREAD

**Issue by KrishnaKishore1992** [docusign/native-ios-sdk#133] opened 2022-11-14 11:31 UTC
Team,

We still have this issue. When trying to open envelope that is created by server by using below function Docusign DSMSigningViewController is presented and dismissed immediately with in seconds. 

I am using latest 3.0.0 iOS SDK

self.mDSMEnvelopesManager?.presentSigning(withPresenting: presentingController, envelopeId: envelopeId, animated: true, completion: { (_, error) in
     if let error = error {
       print("DS Error: ", error)
     }
})

When I added notification observers, DSMSigningCompletedNotification is called and says that document is signed. Actually that document is not signed.

name = DSMSigningCompletedNotification, object = Optional(<DSMSigningViewController: 0x10718d800>), userInfo = Optional([AnyHashable("signingMode"): online, AnyHashable("envelopeId"): 992ca18c-c3ad-41f8-b9e7-18b9a0981bd0])

Similar issue: https://github.com/docusign/native-ios-sdk/issues/12

Could you please help us on this or share small code snippet to load sign the document based on envelope id generated by server.

Thanks in advance.

**Comment by mmohareb** [comment] 2022-11-14 18:09
Hello @KrishnaKishore1992 

Thanks for your report, can we get more details to be able to repro the same issue on our side?
Can you share a sample of the envelope you are using, like a template that we can use to recreate the envelope? 
We checked the envelope id `992ca18c-c3ad-41f8-b9e7-18b9a0981bd0` but we didn't find and tabs on this envelope, so not sure if this is the right envelope you are trying with or not.

Waiting for you reply to be able to address this issue.

**Comment by KrishnaKishore1992** [comment] 2022-11-17 12:23
Sorry missed your message.
Thanks for your reply.
Are tabs are mandatory in the envelope?

**Comment by KrishnaKishore1992** [comment] 2022-11-18 12:12
Added tabs to the envelope id. still same issue Enabled tabs for this envelopeId aa00d6a7-72e0-4f45-90d4-421cfd3cac8c. 

self.mDSMEnvelopesManager?.presentSigning(withPresenting: presentingController, envelopeId: envelopeId, animated: true, completion: { (_, error) in
if let error = error {
print("DS Error: ", error)
}
})

While presenting no errors observed. but DSMSigningCompletedNotification is called & getting this log.

name = DSMSigningCompletedNotification, object = Optional(<DSMSigningViewController: 0x10e03a400>), userInfo = Optional([AnyHashable("envelopeId"): aa00d6a7-72e0-4f45-90d4-421cfd3cac8c, AnyHashable("signingMode"): online])

Could you please help us on this or share small code snippet to load sign the document based on envelope id generated by server.

**Comment by mmohareb** [comment] 2022-11-18 20:34
Hello @KrishnaKishore1992,

I was able to repro the issue you are seeing and the reason is the recipient that is logged into the SDK is different than the one that is assigned to sign this envelope. When both the logged in account and the envelope recipient matched I was able to open the envelope for signature without a problem.

Let us know if this solves the issue for your case or not, we would be happy to jump on a call to check this issue with you.

Here is an example of the envelope looks on the web portal
The person logged in need to match **both the name and email of the Recipient** listed here, if one of the two does not match, the signed in account has no action to perform on this envelope and so the flow ends.
![image](https://user-images.githubusercontent.com/6322177/202796521-ae14d537-7501-4ec9-a6a5-5edacd5f82b7.png)

If you need to share private data about your account or credentials you can send them over to docusignmobilesdk@docusign.com so we can help without compromising the privacy of your data.

**Comment by mmohareb** [comment] 2022-11-30 07:02
After discussion, the root cause of this issue was the logged in user was the sender and not the signer and that caused the signing ceremony to end earlier.
Advised to use Captive signing instead of remote signing since the signer does not have an account.
Resources for Captive signing https://www.docusign.com/blog/developers/embedded-signing-the-native-ios-sdk

**Closed by mmohareb** 2022-11-30 07:02 UTC
Labels: responded
