### ISSUE TITLE
Bug: Receiving authentication error ("unauthorized") after updating to 3.2.0

### ISSUE THREAD

**Issue by keenan-chiasson** [docusign/native-ios-sdk#160] opened 2024-02-09 22:50 UTC
I am currently experiencing a bug after the latest update to 3.2.0 where I am unable to cache my online templates. I am given an error "Account not logged in" when trying to call 

`DSMTemplatesManager().cacheTemplate(withId:)`

My authentication flow passes successfully and I am able to make API calls to things like viewing all my online templates, but the SDK method believes I am logged out. I am correctly setting the login variables with `DSMManager.login(withAccessToken:,
                         accountId:,
                         userId:,
                         userName:,
                         email:,
                         host:,
                         integratorKey:,
                         refreshToken:,
                         expiresIn:, completion:)` and I receive the proper DSMAccountInfo after my successful login. 

Expected Result:
The template is cached successfully with a DSMEnvelopeCachedNotification notification being received

Actual result:
I receive the error "Account not logged in" even though I have successfully logged in.

Note: 
This error wasn't present before updating to 3.2.0 and I have not changed my code since updating

**Comment by mmohareb** [comment] 2024-02-10 00:21
Hello @keenan-chiasson 
Thanks for reaching out, would it be possible to share the network logs capture through a proxy that would be helpful?
Also can you confirm the values you are passing the new params `expiresIn` and `refreshToken` 
maybe if you can share a code snippet for the login steps and how you fetch these info from the Auth API call to the SDK login call, we can try to figure out what is wrong.

if you prefer to share this info directly to our mailbox, you can use the email docusignmobilesdk@docusign.com to communicate this.

Thanks,
Mina.

**Comment by keenan-chiasson** [comment] 2024-02-12 15:05
Thank you for the timely response. I sent an email out with the network log data as well as the swift files that make up my login flow. I noticed today that when I receive the DSMAccountInfo object after login, I also receive the error "unauthorized" along with the object. Hope this helps. Thanks again for your time and speedy responses.

**Comment by keenan-chiasson** [comment] 2024-02-12 17:55
Just tested rolling my DocuSign pod back to '3.1.0' and my authentication flow works perfectly with no code changes. There seems to be a change in the 3.2.0 release that introduces the error

**Comment by mmohareb** [comment] 2024-02-16 17:41
Hello @keenan-chiasson 

We were able to find the root cause of the issue is a missing entry in the info.plist file that allows the SDK to save tokens (Access and refresh) in the key chain
```
<key>AppIdentifierPrefix</key>
<string>$(AppIdentifierPrefix)</string>
```
as per your testing this has resolved the issue, so we will go ahead and close this ticket.

Thanks for sharing the sample app for this issue and working with us on finding the fix.

Best,
Mina.

**Closed by mmohareb** 2024-02-16 17:41 UTC
Labels: ack

**Comment by mmohareb** [comment] 2024-03-01 19:55
Documentation has been updated to add this step.
https://developers.docusign.com/docs/mobile-sdks/ios-sdk/how-to/log-in/
